# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click !here goes the icon of the corresponding button in the gutter! button.
To debug a cell, press Alt+Shift+Enter, or click !here goes the icon of the corresponding button in the gutter! button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [11]:
import numpy as np
import pandas as pd


In [12]:
data = pd.read_csv('data/shortjokes.csv')
data.head()

ID                                               Joke
0   1  [me narrating a documentary about narrators] "...
1   2  Telling my daughter garlic is good for you. Go...
2   3  I've been going through a really rough period ...
3   4  If I could have dinner with anyone, dead or al...
4   5     Two guys walk into a bar. The third guy ducks.

In [13]:
data.columns

Index(['ID', 'Joke'], dtype='object')

In [14]:
data['Joke'] = data['Joke'].apply(lambda x: 'start_of_seq ' + str(x) + ' end_of_seq')

In [15]:
data.head()

ID                                               Joke
0   1  start_of_seq [me narrating a documentary about...
1   2  start_of_seq Telling my daughter garlic is goo...
2   3  start_of_seq I've been going through a really ...
3   4  start_of_seq If I could have dinner with anyon...
4   5  start_of_seq Two guys walk into a bar. The thi...

In [16]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [17]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data['Joke'])

In [18]:
tokenizer.word_index

{'of': 1,
 'seq': 2,
 'start': 3,
 'end': 4,
 'a': 5,
 'the': 6,
 'i': 7,
 'to': 8,
 'you': 9,
 'and': 10,
 'in': 11,
 'my': 12,
 'what': 13,
 'is': 14,
 'it': 15,
 'do': 16,
 'me': 17,
 'on': 18,
 'was': 19,
 'for': 20,
 'that': 21,
 'with': 22,
 'have': 23,
 'why': 24,
 'he': 25,
 'your': 26,
 'when': 27,
 'did': 28,
 'are': 29,
 'like': 30,
 'how': 31,
 'they': 32,
 'if': 33,
 'so': 34,
 'just': 35,
 'at': 36,
 'but': 37,
 'an': 38,
 "i'm": 39,
 'because': 40,
 'one': 41,
 'get': 42,
 'his': 43,
 'be': 44,
 'out': 45,
 'about': 46,
 "don't": 47,
 'call': 48,
 'up': 49,
 'this': 50,
 "it's": 51,
 'not': 52,
 'her': 53,
 'who': 54,
 'can': 55,
 'all': 56,
 'no': 57,
 "what's": 58,
 'say': 59,
 'she': 60,
 'know': 61,
 'people': 62,
 'does': 63,
 'into': 64,
 'from': 65,
 'man': 66,
 'there': 67,
 'said': 68,
 'got': 69,
 'as': 70,
 'we': 71,
 'had': 72,
 'between': 73,
 'them': 74,
 'joke': 75,
 'time': 76,
 'has': 77,
 'go': 78,
 'their': 79,
 'by': 80,
 'would': 81,
 'two': 82,
 'ma

In [19]:
len(tokenizer.word_index)

70649

In [21]:
data = data[:10]

In [24]:
input_sequences = []
for value in data['Joke']:
    tokenized_sentence = tokenizer.texts_to_sequences([value])[0]
    
    for i in range(1, len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

In [25]:
input_sequences

[[3, 1],
 [3, 1, 2],
 [3, 1, 2, 17],
 [3, 1, 2, 17, 9606],
 [3, 1, 2, 17, 9606, 5],
 [3, 1, 2, 17, 9606, 5, 3158],
 [3, 1, 2, 17, 9606, 5, 3158, 46],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84, 100],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84, 100, 13],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84, 100, 13, 152],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84, 100, 13, 152, 383],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84, 100, 13, 152, 383, 1348],
 [3, 1, 2, 17, 9606, 5, 3158, 46, 21294, 7, 84, 100, 13, 152, 383, 1348, 39],
 [3,
  1,
  2,
  17,
  9606,
  5,
  3158,
  46,
  21294,
  7,
  84,
  100,
  13,
  152,
  383,
  1348,
  39,
  391],
 [3,
  1,
  2,
  17,
  9606,
  5,
  3158,
  46,
  21294,
  7,
  84,
  100,
  13,
  152,
  383,
  1348,
  39,
  391,
  4],
 [3,
  1,
  2,
  17,
  9606,
  5,
  3158,
  46,
  21294,
  7,
  84,
  100,
  13,

In [26]:
max_len = max([len(x) for x in input_sequences])
max_len

29

In [27]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  3,  1],
       [ 0,  0,  0, ...,  3,  1,  2],
       [ 0,  0,  0, ...,  1,  2, 17],
       ...,
       [ 0,  0,  0, ..., 20, 17,  4],
       [ 0,  0,  0, ..., 17,  4,  1],
       [ 0,  0,  0, ...,  4,  1,  2]])

In [28]:
X = padded_input_sequences[:, :-1]
Y = padded_input_sequences[:, -1]
(X, Y)

(array([[  0,   0,   0, ...,   0,   0,   3],
        [  0,   0,   0, ...,   0,   3,   1],
        [  0,   0,   0, ...,   3,   1,   2],
        ...,
        [  0,   0,   0, ..., 301,  20,  17],
        [  0,   0,   0, ...,  20,  17,   4],
        [  0,   0,   0, ...,  17,   4,   1]]),
 array([    1,     2,    17,  9606,     5,  3158,    46, 21294,     7,
           84,   100,    13,   152,   383,  1348,    39,   391,     4,
            1,     2,     1,     2,   576,    12,   565, 10179,    14,
          103,    20,     9,   103, 10180,  1452,    10,   741, 28512,
          253, 10499, 10848,  3139,   206,     4,     1,     2,     1,
            2,   132,   127,   109,   294,     5,   104,  3360,   831,
           36,   174,    50,   465,    51,    12,   341,  2088,    20,
        19240,    12, 12604,    20,  2226,   505,     4,     1,     2,
            1,     2,    33,     7,   151,    23,   519,    22,   366,
          218,   105,  1086,     7,    81,  1568,  1086,   609,  1498,
     

In [29]:
X.shape, Y.shape

((207, 28), (207,))

In [30]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(Y, num_classes=len(tokenizer.word_index)+1)
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [31]:
y.shape

(207, 70650)

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [33]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=max_len))
model.add(LSTM(units=150))
model.add(Dense(len(tokenizer.word_index) + 1, activation= 'softmax'))

C:\Users\shahabuddin akhon hr\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 28, 100)        │     7,065,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 70650)          │    10,668,150 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,883,750 (68.22 MB)

 Trainable params: 17,883,750 (68.22 MB)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.fit(X, y, epochs=10)

Epoch 1/10
1/7 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

ValueError: Cannot get result() since the metric has not yet been built.

In [ ]:
import time
import numpy as np
text = "start_of_seq Telling my daughter garlic is good for you."

for i in range(20):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)